### PR TITLE
Fix windows' builds aapt/aapt2

### PR DESCRIPTION
**Pull request by iBotPeaches**

### CODE REVIEW

**Comment by iBotPeaches** [comment]
Hi @Furniel,

Does this make any sense? The above changes fix the windows binaries for me, but I don't see why. I basically undid the Soong convert for aapt1 which somehow fixed the binaries linking stage.

I want to keep the Soong stuff though, because it makes building both archs very easy, as opposed to the messy make files.

**Comment by Furniel** [comment]
@iBotPeaches 
Hm, no sense for me - this change was simply [backported from master branch](https://android-review.googlesource.com/c/platform/frameworks/base/+/741568)  and it shoudn't break anything as many other tools already use soog. And i totaly don't understand how upgrading of aapt1 build system can break aapt2 builds too. Did you tried to build x64 aapt builds seperatly? Maybe there's some problem with suffixes? Can you test this change(same changes can be done for aapt2)?
```
cc_binary_host {
    name: "aapt",
    defaults: ["aapt_defaults"],
    srcs: ["Main.cpp"],
    use_version_lib: true,
    static_executable: true,
    static_libs: ["libaapt"],
    compile_multilib: "64", //Removed x86 support here, left only x64
   //disable suffix, as we build only one version of aapt
    //multilib: {
    //    lib64: {
    //        suffix: "_64",
    //    },
    //},
}
```
And what commands do you use to build windows binaries? Maybe there is some problem in build sequence?
I use this commands for aapt builds for windows:
```
. build/envsetup.sh
lunch sdk-eng
make host_cross_aapt       //x86 aapt build
make host_cross_aapt_64    //x64 aapt build
make host_cross_aapt2      //x86 aapt2 build
make host_cross_aapt2_64   //x64 aapt2 build
```

**Comment by Furniel** [comment]
Tested your build commands and got fully working binaries too(aosp master branch), so looks like problem is not in build commands. Have no more ideas why x64 binaries can be broken.

**Comment by iBotPeaches** [comment]
Thanks, I'll nuke my install and reclone. I haven't tried master yet though, so I'll do that. I've been using the `android-9.0.0_r30` or `android-9.0.0_r22` tag.

**Comment by iBotPeaches** [comment]
There is an astronomic huge list of changes between `master` and even the latest `android-9.0.0_r30` tag. This is an absolute mess.

I've been using tags of releases to have some sort of organization to aapt releases vs master builds, but it seems this train of thinking was completely wrong. Even just the `tools` folder has more changes than I can count.

I guess my options.

1) Revert Soong changes, as they must not be ready to map on top of the Pie tag.
2) Update myself to master
3) Investigate issue further, so that the modified apktool `frameworks/base` tag works with the tag I use

**Comment by IgorEisberg** [comment]
Guys, any idea why I get ~15MB aapt and ~50MB aapt2 Linux binaries (and even larger Windows binaries) when I build using those commands?
Nothing like the tiny sizes of the pre-included binaries in Apktool. :/

**Comment by iBotPeaches** [comment]
Upgraded to master AOSP, closing this.

**Pull request closed without merging**
