### PR TITLE
Bring back x86 aapt(2) build support

### PR DESCRIPTION
**Pull request by Furniel**
With this changes aapt and aap2 x86 and x64 versions can be built. Also i enabled fully static build of executables and backported "Convert aapt to Soong" patch from master. Linux and macos versions can be built simply with "make aapt(2)", but windows x64 version will be built only with "make host_cross_aapt(2)_64" commands.(Seems "compile_multilib: "both"" doesn't work for windows)

PS:  I'm not sure if you want bring back x86 support to apktool.

### CODE REVIEW

**Comment by iBotPeaches** [comment]
Sorry for leaving this sit. I am debating internally with the other open pull request regarding 32bit support. I appreciate the patching of soong for aapt1

**Comment by iBotPeaches** [comment]
@Furniel Looking for opinions, is returning x86 support something that you want/need? I am trying to build out use cases, because supporting this many platforms that will require rebuilds on each aapt change makes me nervous. From a maintenance/maintainer point of view. Duplicated this question to the open pull request for adding arm support - https://github.com/iBotPeaches/Apktool/pull/1878#issuecomment-435182187

**Comment by Furniel** [comment]
@ibotpeaches
Personally I don't need x86 linux aapt support, but some users on xda complained when x86 arch was dropt. I made this changes to make it possible compile x64 aapt versions for Windows(official version is x86) - it's simply works faster than x86. At this moment we don't need many changes for x86 and x64 builds support, so it's not hard to make some x86 linux users happy and may be x64 windows users too.
PS: i'm not sure that there are many linux users that need x86 support, so i agree that it may be bad idea bring back something that was dropped long time ago and even not supported by google.

**Comment by iBotPeaches** [comment]
Thanks for the response. I am choosing to keep 32 dropped. Future mac releases further this agenda of killing off 32bit and Google itself doesn't seem to be liking it.

> Mac OSX 10.14 Mojave deprecates 32-bit executables, and the 10.14 SDK does not successfully link 32-bit files.
https://android-review.googlesource.com/c/platform/build/+/740646

I appreciate the other changes and will get those merged.

**Comment by iBotPeaches** [comment]
Sorry for the delay on this. I appreciate this change for the updated patches for static builds. Merged

**Pull request merged**
