### PR TITLE
Add option to specify a file containing a list of file extensions that should not be compressed.

### PR DESCRIPTION
**Pull request by peret**
This makes it possible to specify a doNotCompress list with a lot of
entries on systems that have a restriction on the length of the command
line (i.e. Windows and Mac OS).

By adding this option, we now have an easy way to fix [Issue 1272](https://github.com/iBotPeaches/Apktool/issues/1272) in Apktool.

I'm not quite sure about the structure of this repo. Was it correct to base this on the apktool_9.0.0 branch? If not, let me know and I can change it.

### CODE REVIEW

**Comment by iBotPeaches** [comment]
Interesting workaround. So we just populate a file with our structure and patch aapt to handle this. My only fear is both aapt/aapt2 would have to be patched. 

I need to research a bit more, because I forgot what we are looking at aapt1 vs aapt2.

**Comment by peret** [comment]
Exactly! I also opened a [PR in the apktool repo](https://github.com/iBotPeaches/Apktool/pull/2192) with code changes required to use this new option.

What exactly are your concerns? I changed both aapt and aapt2 and it seems to work as intended for both versions. Luckily, this part of the aapt command line interface didn't really change between versions, at least i as far as I can see.

**Comment by iBotPeaches** [comment]
Apologies. Only one file expanded on mobile. I'll take a look again when home.

**Comment by peret** [comment]
Ah, I see! No problem!

Connor Tumbleson <notifications@github.com> schrieb am So., 6. Okt. 2019,
14:24:

**Comment by peret** [comment]
Hi @iBotPeaches, did you have a chance to look into this yet? :)

**Comment by iBotPeaches** [comment]
thanks again!

**Pull request merged**
